const events=[
 {date:'Aug 14',type:'NOTICE',title:'Notice of Violation received',detail:'Exterior structure and property-maintenance allegations. Source: uploaded notice, page 1–3.'},
 {date:'Aug 18',type:'DEADLINE',title:'Compliance period ends',detail:'14-day response window identified from the notice. Verify the governing ordinance before relying on this date.'},
 {date:'Aug 22',type:'INSPECTION',title:'Inspection scheduled',detail:'Agency inspection appointment appears in correspondence. Confirmation is still needed.'},
]
const issues=[
 ['Action required soon','A response deadline is approaching. Gather supporting evidence and confirm the applicable rule before sending anything.','warn'],
 ['Service evidence incomplete','The case currently contains the notice but no independently verified service record.','critical'],
 ['Permit relationship unclear','A permit reference appears in the evidence set but is not yet linked to the alleged violation.','info']
]
export default function Home(){return <div className="shell">
 <aside className="sidebar"><div className="brand">My-CoMind <span>/ Code Enforcement</span></div><nav className="nav"><a className="active" href="#">Command Center</a><a href="#timeline">Timeline</a><a href="#violations">Violations</a><a href="#evidence">Evidence</a><a href="#property">Property Intelligence</a><a href="#issues">Issues & Findings</a><a href="#actions">Actions</a><a href="#communications">Communications</a></nav><div style={{marginTop:'auto'}} className="muted">Evidence-first civic workflow<br/>v0.1 foundation</div></aside>
 <main className="main"><div className="top"><div><div className="eyebrow">Active case · Humboldt County</div><h1 className="title">1450 Example Road</h1><div className="muted">Case CE-2026-01482 · APN 000-000-000 · Code Enforcement</div></div><div className="actions"><button className="btn">Upload evidence</button><button className="btn primary">Ask Case AI</button></div></div>
 <div className="search"><input placeholder="Search case, evidence, ordinance, event, or ask a question…"/><button className="btn">Analyze</button></div>
 <div className="grid"><div className="card"><div className="label">Case status</div><div className="metric">Open</div><div className="muted">Agency action pending</div></div><div className="card"><div className="label">Next deadline</div><div className="metric">Aug 18</div><div className="muted">1 day remaining</div></div><div className="card"><div className="label">Evidence</div><div className="metric">18</div><div className="muted">3 need review</div></div><div className="card"><div className="label">Open issues</div><div className="metric">3</div><div className="muted">1 critical · 1 warning</div></div></div>
 <div className="layout"><section className="card" id="timeline"><div className="section-title"><span>Case timeline</span><span className="pill">Evidence-linked</span></div><div className="timeline">{events.map((e,i)=><div className="event" key={i}><div className="date">{e.date}<br/><span className="pill">{e.type}</span></div><div><h3>{e.title}</h3><div className="muted">{e.detail}</div></div></div>)}</div><button className="btn" style={{marginTop:12}}>View full timeline</button></section>
 <aside className="card" id="issues"><div className="section-title"><span>Issues & findings</span><span className="pill critical">Needs attention</span></div>{issues.map((x,i)=><div className="issue" key={i}><strong>{x[0]}</strong><span className={'pill '+(x[2]==='critical'?'critical':x[2]==='warn'?'warn':'')} style={{float:'right'}}>{x[2]}</span><p>{x[1]}</p></div>)}<button className="btn" style={{marginTop:14,width:'100%'}}>Run procedural analysis</button></aside></div>
 <div className="quick"><div className="card"><b>Violations</b><p>Track each alleged violation, code citation, inspection, cure requirement, and supporting evidence.</p></div><div className="card"><b>Evidence vault</b><p>Preserve notices, photos, permits, correspondence and public records with provenance and source references.</p></div><div className="card"><b>Case AI</b><p>Ask questions against the case record. Answers distinguish facts, inferences, unknowns, rules, and recommendations.</p></div></div>
 </main></div>}
